Update deploy-terrafrom.yml

diff --git a/.github/workflows/deploy-terrafrom.yml b/.github/workflows/deploy-terrafrom.yml
--- a/.github/workflows/deploy-terrafrom.yml
+++ b/.github/workflows/deploy-terrafrom.yml
@@ -22,7 +22,7 @@ jobs:
           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
       - name: Deploy to EC2
-        uses: appleboy/ssh-action@v0.1.1
+        uses: appleboy/ssh-action@v0.1.2  # Check for the latest version
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
@@ -31,10 +31,10 @@ jobs:
           script: |
             set -x
             echo "Starting deployment"
-            cd /home/ubuntu/medusa || exit
-            sudo docker-compose pull || exit
-            sudo docker-compose down || exit
-            sudo docker-compose up -d || exit
+            cd /home/ubuntu/medusa || { echo "Failed to change directory"; exit 1; }
+            sudo docker-compose pull || { echo "Failed to pull Docker images"; exit 1; }
+            sudo docker-compose down || { echo "Failed to stop Docker containers"; exit 1; }
+            sudo docker-compose up -d || { echo "Failed to start Docker containers"; exit 1; }
             echo "Deployment finished"
           debug: true
           timeout: 10m
